import { NavBar } from "@/components/NavBar";
import "./globals.css";
import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import Context from "@/Context";

const OpenSans = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={OpenSans.className}>
        <Context>
          <NavBar />
          <div className="md:my-[68px] my-14">{children}</div>
        </Context>
      </body>
    </html>
  );
}
